export interface IProvider {
  id: string;
  companyName: string;
  email: string;
  mobile: string;
  password: string;
  airlineCode: string;
  role: "provider";
  logoUrl?: string;
  registrationCertificateUrl?: string;
  insuranceProofUrl?: string;
  establishmentYear?: number;
  licenseExpiryDate?: Date;
  headquartersAddress?: string;
  countryOfOperation?: string;
  typeOfOperation?: string;
  websiteUrl?: string;
  ceoName?: string;
  officeContactNumber?: string;
  commissionRate: number; 
  createdAt: Date;
  updatedAt: Date;
  isActive: boolean;
  isVerified: boolean;
  otpVerified?: boolean;
  adminApproval: boolean; 
  isProfileComplete: boolean; 
  profileStatus: 'pending' | 'approved' | 'rejected';
  rejectionReason?: string |null;
  rejectionDate?: Date |null;
}